name: ai_notes_taker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.4.3+1
  shared_preferences: ^2.5.1
  http: ^1.2.1
  http_parser: ^4.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.8
  firebase_crashlytics: ^4.3.8
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  local_auth: ^2.3.0
  flutter_sound: ^9.28.0
  flutter_tts: ^4.2.3
  android_alarm_manager_plus: ^4.0.8
  alarm: ^4.0.0
  google_fonts: ^6.1.0
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^6.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  slang_build_runner: ^3.31.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/

slang:
  base_locale: en
  fallback_strategy: base_locale
  input_directory: lib/i18n
  input_file_pattern: .i18n.json
  output_directory: lib/i18n
  output_file_name: translations.g.dart
  output_format: single_file
  locale_handling: true
  flutter_integration: true
  namespaces: false

