// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj73Z9OlgYbFGY9FXh8tsYHU7oemFbiqQ',
    appId: '1:179880515307:web:02803847c5b3571f1350ae',
    messagingSenderId: '179880515307',
    projectId: 'ai-notes-taker-8dbf6',
    authDomain: 'ai-notes-taker-8dbf6.firebaseapp.com',
    storageBucket: 'ai-notes-taker-8dbf6.firebasestorage.app',
    measurementId: 'G-HRYKF06Q1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-1UR8IGePkg1Ng34VUogkPXg2ibGKGI',
    appId: '1:179880515307:android:a46287d9e4b455061350ae',
    messagingSenderId: '179880515307',
    projectId: 'ai-notes-taker-8dbf6',
    storageBucket: 'ai-notes-taker-8dbf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbPaqgRqyu77cwHWEoMyxe2iE1omDIZg',
    appId: '1:179880515307:ios:ee6125c939a209a21350ae',
    messagingSenderId: '179880515307',
    projectId: 'ai-notes-taker-8dbf6',
    storageBucket: 'ai-notes-taker-8dbf6.firebasestorage.app',
    iosBundleId: 'com.example.aiNotesTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbPaqgRqyu77cwHWEoMyxe2iE1omDIZg',
    appId: '1:179880515307:ios:ee6125c939a209a21350ae',
    messagingSenderId: '179880515307',
    projectId: 'ai-notes-taker-8dbf6',
    storageBucket: 'ai-notes-taker-8dbf6.firebasestorage.app',
    iosBundleId: 'com.example.aiNotesTaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj73Z9OlgYbFGY9FXh8tsYHU7oemFbiqQ',
    appId: '1:179880515307:web:e33c5d669094c30f1350ae',
    messagingSenderId: '179880515307',
    projectId: 'ai-notes-taker-8dbf6',
    authDomain: 'ai-notes-taker-8dbf6.firebaseapp.com',
    storageBucket: 'ai-notes-taker-8dbf6.firebasestorage.app',
    measurementId: 'G-C8FEMNEB82',
  );
}
